### ISSUE TITLE
User expects local locale

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/stodt#11]
Especially European users expect date to be formatted in a local locale. Most of the users have difficulty to understand that 03/09/2020 is the 9th of march and not a forecast for September.

![Screenshot from 2020-03-09 17-27-56](https://user-images.githubusercontent.com/414797/76235416-58229a80-622b-11ea-8483-924706dfa7c8.png)

**Comment by ivoputzer** [comment]
@ohnewein the way this field is shown depends on your os and browser configuration. The format used to display dates within this input field depends on your locale already. 

For Italian configurations you might get:
![image](https://user-images.githubusercontent.com/1570449/76849558-e909ff00-6845-11ea-8cdb-1727aa4d096e.png)


What configuration are you using?

**Comment by ohnewein** [comment]
Hi @ivoputzer ,

it looks as if the browser didn't use the locale I have set system wide. Looks like everything works fine now.

Thank you!
Patrick

**Comment by Piiit** [comment]
@ivoputzer @ohnewein I think this is solved, so I close it now, feel free to reopen if necessary :-)
