### ISSUE TITLE
As a developer of STODT, I want to have a CI and CD pipeline, and see results online

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/stodt#6]
Some bugs prevent local testing, we need to fix them before...
- https://github.com/noi-techpark/stodt/issues/4 @giacomo-montibeller 
- https://github.com/noi-techpark/stodt/issues/8 @giacomo-montibeller 
> We follow these issues separately, we managed to deploy it nevertheless...
- [x] Deploy production on https://stodt.davinci.bz.it (+CD pipeline) @Piiit 
    - [x] Error occurred `TASK [ansible-docker-deployment : Log into AWS ECR docker registry] ************
fatal: [docker02.testingmachine.eu]: FAILED! => {"changed": true, "cmd": "aws ecr get-login-password | docker login --username AWS --password-stdin 755952719952.dkr.ecr.eu-west-1.amazonaws.com", "delta": "0:00:00.741991", "end": "2020-03-20 15:49:03.590463", "msg": "non-zero return code", "rc": 1, "start": "2020-03-20 15:49:02.848472", "stderr": "\nAn error occurred (AccessDeniedException) when calling the GetAuthorizationToken operation: User: arn:aws:sts::755952719952:assumed-role/Monitoring/i-0ce5a358832d53a04 is not authorized to perform: ecr:GetAuthorizationToken on resource: *\nError: Cannot perform an interactive login from a non TTY device", "stderr_lines": ["", "An error occurred (AccessDeniedException) when calling the GetAuthorizationToken operation: User: arn:aws:sts::755952719952:assumed-role/Monitoring/i-0ce5a358832d53a04 is not authorized to perform: ecr:GetAuthorizationToken on resource: *", "Error: Cannot perform an interactive login from a non TTY device"], "stdout": "", "stdout_lines": []}
`
- [x] Add a FESR logo
- [x] Deploy testing on https://stodt.davinci.testingmachine.eu (+CD pipeline) @Piiit 
- [x] Move internal deployment to docker02.testingmachine.eu, because docker01 is already swapping memory :-)

**Comment by Piiit** [comment]
@ivoputzer @sseppi @LucaMiotto @giacomo-montibeller @ZimmerhoferHarald 

Please test... If it is OK like that, I can get to production on https://stodt.davinci.bz.it/...

**Comment by ohnewein** [comment]
I get the following error message:

> *DNS lookup failure for: docker02.opendatahub.bz.it*

*
**
*

**Comment by Piiit** [comment]
@ohnewein That is because the production server is not setup, as you see in this issue, I wait to get the OK for the test server, so I can setup the production

**Comment by Piiit** [comment]
@ohnewein The test server is on https://stodt.davinci.testingmachine.eu/

**Comment by ivoputzer** [comment]
@Piiit stodt.davinci.testingmachine.eu LGTM! What do you think @giacomo-montibeller @danielefongo?

**Comment by ohnewein** [comment]
Great, I tested it and have started inserting some issues:

https://github.com/noi-techpark/stodt/issues

**Comment by Piiit** [comment]
@alexlanz Blocked due to a Docker issue, asked Alex since he added "Monitoring" to it, which blocks the deployment now

**Comment by Piiit** [comment]
@ohnewein @ZimmerhoferHarald @ivoputzer @sseppi @LucaMiotto @giacomo-montibeller @danielefongo
It is released on https://stodt.davinci.bz.it/... Thanks to all contributors :-)
And please write me, if you like to add more information in the description field below the title

**Comment by ohnewein** [comment]
Dear SFScon friend,

hereby I forward you the official invitation to this year's SFScon.

The conference will take place on *Friday, November 13th* from 9:00 AM
to 6:00 PM (CET) and *Saturday 14th* from 9:00 AM to 1:00 PM (CET).

Free tickets and online streaming available on https://www.sfscon.it

The event is held in *English only*.

Participation is free of charge thanks to our sponsors: Huawei,
Telmekom, Red Hat, Made in Cima, 1006.org, Catch Solve, Endian, Gruppo
Fos, Peer, QBus, R3Gis and SiMedia.

Kind regards,
Patrick

----------------------------------

Liebe SFScon Freunde,

anbei leite ich euch die offizielle Einladung zur SFScon weiter.

Die Konferenz wird am *Freitag**, den 13. November* von 9:00 bis 18:00
Uhr (CET) und *Samstag**14.* von 9:00 bis 13:00 Uhr (CET) stattfinden.

Die Veranstaltung wird in *Englisch* abgehalten.

Dank unserer Sponsoren Huawei, Telmekom, Red Hat, Made in Cima,
1006.org, Catch Solve, Endian, Gruppo Fos, Peer, QBus, R3Gis und SiMedia
ist die Teilnahme kostenlos.

Kostenlose Registrierung und *Online-Streaming* findet ihr auf
https://www.sfscon.it

Liebe Grüße,
Patrick

----------------------------------

Caro amico della SFScon,

ti inoltro l'invito ufficiale alla SFScon.

La conferenza si terrà *venerdì 13 novembre* dalle 9 alle 18 (CET) e
*sabato 14* dalle 9 alle 13 (CET).

Tutti gli interventi si svolgeranno in *i**nglese* e verranno trasmessi
via *video streaming*.

Grazie ai nostri sponsor Huawei, Telmekom, Red Hat, Made in Cima,
1006.org, Catch Solve, Endian, Gruppo Fos, Peer, QBus, R3Gis e SiMedia
la partecipazione é gratuita e puoi registrarti sul sito dell'evento:
https://www.sfscon.it

Con i migliori saluti
Patrick


-------- Forwarded Message --------
Subject: 	SFScon 2020 INVITATION
Date: 	Tue, 03 Nov 2020 14:26:15 +0000
From: 	SFScon <sfscon@noi.bz.it>
Reply-To: 	SFScon <sfscon@noi.bz.it>
To: 	p.ohnewein@noi.bz.it



NOI Techpark Newsletter


NOI Techpark <https://noi.bz.it> 	


    *SFScon 2020 INVITATION*

	

Dear SFScon Friends,

We are proud to invite you to the *#SFScon20*, an opportunity to discuss
together with international experts how Free Software, Open Standards
and Open Data can contribute in identifying disruptive Business Models
in the Industry and creating innovative products using Open Technologies.

The conference will take place on *Friday, November 13th* from 9:00 AM
to 6:00 PM (CET) and *Saturday 14th* from 9:00 AM to 1:00 PM (CET).

You can participate at SFScon only via online streaming. Due the current
situation, it has been decided to minimise live access (last year there
were more than 1000 participants) and give interested parties the
opportunity to follow the conference remotely on *www.sfscon.it*
<https://www.sfscon.it>.

Still, our aim is to provide speakers with the feeling of being present
at a conference, by contributing the necessary infrastructure to take
part online.

We are pleased to welcome almost 100 internationally recognised experts
from around the world, including Davide Ricci (Open Source Technology
Center, Huawei), Simon Ebnicher (Telmekom), Oliver Fendt (Siemens),
Andrew Wilson, Simon Phipps, Gianluca Antonacci (CISMA), Florian
Effenberger (The Document Foundation), Reto Schneider (Gardena,
Husqvarna Group), Cédric Thomas (OW2), Margherita Cera (Rödl & Partner),
Rowan Wilson (University of Oxford), Diego Calvanese (Free University of
Bozen-Bolzano) and many more.

You can find schedule details and registration on the event website:
*www.sfscon.it* <https://www.sfscon.it>.

Please note that all times are expressed in Central European Time *(CET)
UTC+01:00*. The program is still subject to modification and will be
continuously updated until the conference.

The event is held in *English only*.

Participation is free of charge thanks to our sponsors: Huawei,
Telmekom, Red Hat, Made in Cima, 1006.org, Catch Solve, Endian, Gruppo
Fos, Peer, QBus, R3Gis and SiMedia.

We are looking forward to seeing you on screen.

Your NOI-Team

	


          *Say hello
          for more information*

	

*Patrick Ohnewein*

	

T +39 0471 066 675
sfscon@noi.bz.it <mailto:sfscon@noi.bz.it>

	

Pin

Via Volta 13/A
39100 Bolzano - Italia

	

*noi.bz.it* <https://noi.bz.it>


------------------------------------------------------------------------
	


Instagram <https://www.instagram.com/noi.techpark> 	Facebook
<https://www.facebook.com/NOI.Techpark/> 	Linkedin
<https://www.linkedin.com/company/noitechpark> 	Twitter
<https://twitter.com/noi_techpark> 	Youtube
<https://www.youtube.com/channel/UCadhbHbqZUw8gkKFOVGt4mQ>


	

Ricevi questa comunicazione all’indirizzo e-mail p.ohnewein@noi.bz.it,
perché fai parte della nostra rete.
*Puoi aggiornare qui le tue preferenze.*
<https://registration.noi.bz.it/subscriptionit?msdynunsubscribeid=wx4GZzT9xQoM3xX1CTxHLcRx9OyMAQeuNIccKoVgxRgx>.

NOI SpA - P.IVA 02595720216

A.-Volta-Straße / Via A. Volta, 13A I-39100 Bozen / Bolzano

**Comment by ohnewein** [comment]
Dear SFScon friend,

I am proud to invite you to this years SFScon, the annual conference 
about Free Software in Bolzano/Bozen.

The *conference will be held on November 12th and 13th* at NOI Techpark 
in Bolzano/Bozen, Italy.
SFScon will take place in blended mode or, if conditions make it 
necessary, online only.

Participation is free of charge and registration is available on the 
events website:

https://www.sfscon.it

I would also like to remind you about the *deadline for submissions of 
talk proposals by June 30th*. Use the instructions to submit your proposal:

https://www.sfscon.it/call-4-speakers/

We are looking forward to read all your talk abstracts and to meet you 
at the SFScon 2021!

We will publish all information about speakers, talks, side events and 
more on the conference website:

https://www.sfscon.it

Let's keep in touch!

Best wishes
Patrick

--------------------------

Lieber SFScon Freund,

ich bin sehr froh dich auch heuer wieder zur SFScon, die Konferenz zu 
Freier Software in Bozen, einzuladen.

Die *Konferenz wird am 12. und 13. November* im NOI Techpark (online und 
offline) oder falls notwendig, online stattfinden.

Die Teilnahme ist kostenlos, Anmeldung ist auf der Veranstaltungsseite 
möglich:

https://www.sfscon.it

Wir möchten dich außerdem an die *Fälligkeit zur Einreichung von 
Vorträgen erinnern, welche auf den 30. Juni gesetzt ist*.

Informationen zur Einreichung von Abstracts für Vorträge sind auf 
folgender Seite verfügbar:

https://www.sfscon.it/call-4-speakers/

Wir freuen uns auf deine Vorschläge und dich auf der SFScon 2021 zu treffen!

Informationen zu Vorträgen, Vortragenden, Rahmenprogramm und allem 
anderen zur SFScon werden wir auf der Veranstaltungswebseite 
veröffentlichen:

https://www.sfscon.it

Liebe Grüße,
Patrick

--------------------------

Caro amico della SFScon,

sono orgoglioso di invitarti alla SFScon di quest'anno, la conferenza 
annuale sul Free Software a Bolzano.

*La conferenza si terrà il 12 e 13 novembre* al NOI Techpark di Bolzano.
La SFScon si svolgerà in modalità blended o, se le condizioni lo 
renderanno necessario, solo online.

La partecipazione è gratuita, puoi registrarti sul sito dell'evento:

https://www.sfscon.it

Vorremmo anche ricordarti la *scadenza per la presentazione delle 
proposte di talk entro il 30 giugno*. Vedi le istruzioni per inviare le 
tue proposte:

https://www.sfscon.it/call-4-speakers/

Non vediamo l'ora di leggere tutti gli abstract dei tuoi interventi e di 
incontrarti alla SFScon 2021!

Pubblicheremo tutte le informazioni su relatori, talk, eventi 
collaterali ed altro sul sito della conferenza:

https://www.sfscon.it

Con i migliori saluti
Patrick

-- 
Digital Technologies
Patrick Ohnewein
Head of Unit

T +39 0471 066 670
***@***.*** ***@***.***>

*NOI Techpark Südtirol / Alto Adige*
A.-Volta-Straße / Via A. Volta, 13A
I-39100 Bozen / Bolzano
www.noi.bz.it <https://www.noi.bz.it>
